---

# defines containers used to integrate management applications
# name: container name (unique)
# roles: corresponds to ansible role used to deploy application
# release: ubuntu release to be used, e.g. trusty
# ports: list of dictionaries that contains port mappings
#   name: the name of the port mapping
#   host: the port on the host side
#   container: the port on the container side
# mount: mount point for host shared directory
# address: ipv4 address (optional, used if static address)
# netmark: ipv4 netmask (optional, used if static address)
# broadcast: ipv4 broadcast (optional, used if static address)
# gateway: ipv4 gareway (optional, used if static address)
# nameserver: ipv4 nameserver (optional, used if static address)
#
containers:
  - name: nagios1
    role: nagios
    release: trusty
    ports:
      - { name: "http", host: 8001, container:   80 }
      - { name: "nrpe", host: 5601, container: 5666 }
    mount: usr/local/nagios/opsmgr/nagios_config
  - name: nagios2
    role: nagios
    release: trusty
    ports:
      - { name: "http", host: 8002, container:   80 }
      - { name: "nrpe", host: 5602, container: 5666 }
    mount: usr/local/nagios/opsmgr/nagios_config


