---

# opsmgr version
opsmgr_version: 0.9.9

# opsmgr directory
opsmgr_dir: "{{ playbook_dir }}/.."

# tweak use of pip
pipexec: pip
pipargs: ''

# name of sudoers file
sudoers_filename: opsmgr_sudoers

# internal database
db_name: opsmgr
mysql_root_user: root
mysql_root_password: passw0rd

# proxy mode - valid values: iptables or haproxy
# obs: it doesn't actually install packages, just configure
proxy_mode: haproxy

# mtu to use for new interfaces
lxc_container_default_mtu: 1500

# defines containers used to integrate management applications
# name: container name (unique)
# roles: corresponds to ansible role used to deploy application
# release: ubuntu release to be used, e.g. trusty
# ports: list of dictionaries that contains port mappings
#   name: the name of the port mapping
#   host: the port on the host side
#   container: the port on the container side
# mount: mount point for host shared directory
# address: ipv4 address (optional, used if static address)
# netmark: ipv4 netmask (optional, used if static address)
# broadcast: ipv4 broadcast (optional, used if static address)
# gateway: ipv4 gareway (optional, used if static address)
# nameserver: ipv4 nameserver (optional, used if static address)
#
containers:
  #- name: core
  #  role: core
  #  release: trusty
  #  ports:
  #    - { name: "http", host: 8000, container:   80 }
  #  mount: etc/opsmgr/shared
  #- name: mysql
  #  role: mysql
  #  release: trusty
  #  ports:
  #    - { name: "mysql", host: 3306, container: 3306 }
  #  mount: etc/opsmgr/shared
  - name: nagios
    role: nagios
    release: trusty
    ports:
      - { name: "http", host: 8001, container:   80 }
      - { name: "nrpe", host: 5601, container: 5666 }
    mount: usr/local/nagios/opsmgr/nagios_config

create_lxc_network: true
main_lxc_interface: eth1
address_pool: [ 172.29.236.41, 172.29.236.42, 172.29.236.43, 172.29.236.44, 172.29.236.45, 172.29.236.46, 172.29.236.47, 172.29.236.48, 172.29.236.49 ]

# lxc container networks
# defines additional networks to be created 
container_networks:
  - name: mgmt
    bridge: "br-mgmt"
    interface: "eth1"
    netmask: "255.255.252.0"
    type: "veth"



