---
# Copyright 2017, IBM US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Installing ES on Ubuntu 16.04 requires
# an older JDK then is available
# so another repo is used.
# In order to install the JDK on
# Power an prereq package is required

- name: Download preq jre packages
  get_url:
    url: "{{ item.url }}/{{ item.file }}"
    dest: "/tmp/{{ item.file }}"
  with_items: "{{ jre_preq_packages }}"
  when: ansible_architecture == 'ppc64le'
  tags:
    - elasticsearch-deb-package
    - elasticsearch-pre-install

- name: Install preq deb packages (ppc64le)
  apt:
    deb: "/tmp/{{ item.file }}"
    state: installed
  with_items: "{{ jre_preq_packages }}"
  when: ansible_architecture == 'ppc64le'
  tags:
    - elasticsearch-deb-package
    - elasticsearch-pre-install

- name: Remove the preq deb package in /tmp (ppc64le)
  file:
    path: "/tmp/{{ item.file }}"
    state: absent
  with_items: "{{ jre_preq_packages }}"
  when: ansible_architecture == 'ppc64le'
  tags:
    - elasticsearch-deb-package
    - elasticsearch-pre-install

- name: Add apt repositories
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items: "{{ jre_repos }}"
  register: add_repos
  until: add_repos|success
  retries: 5
  delay: 2
  tags:
    - jre-apt-repos
    - elasticsearch-pre-install

- name: Install jre
  apt:
    pkg: "{{ jre_package }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
    allow_unauthenticated: yes
  register: install_apt_packages
  until: install_apt_packages|success
  retries: 5
  delay: 2
  tags:
    - jre-apt-packages
    - elasticsearch-pre-install
