---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Download deb/rpm package
  get_url:
    url: "{{ item.url }}/{{ item.file }}"
    dest: "/tmp/{{ item.file }}"
  with_items: "{{ elasticsearch_packages }}"
  tags:
    - elasticsearch-package
    - elasticsearch-install

- name: installs elasticsearch from deb
  apt:
    deb: "/tmp/{{ item.file }}"
    state: present
  with_items: "{{ elasticsearch_packages }}"
  when: ansible_os_family == "Debian"
  register: install_deb
  until: install_deb|success
  retries: 5
  delay: 2
  tags:
    - elasticsearch-package
    - elasticsearch-install

- name: installs elasticsearch from rpm
  package:
    name: "/tmp/{{ item.file }}"
    state: present
  with_items: "{{ elasticsearch_packages }}"
  when: ansible_os_family == "RedHat"
  register: install
  until: install|success
  retries: 5
  delay: 2
  tags:
    - elasticsearch-package
    - elasticsearch-install

- name: remove deb/rpm file
  file:
    path: "/tmp/{{ item.file }}"
    state: absent
  with_items: "{{ elasticsearch_packages }}"
  tags:
    - elasticsearch-package
    - elasticsearch-install

#Patch /usr/share/elasticsearch/bin/plugin to remove
#the -client option is not available in ppc64le
- name: Patch plugin
  shell: awk '{gsub("-client ","");print}' plugin > plugin.new
  args:
    chdir: /usr/share/elasticsearch/bin
    creates: /usr/share/elasticsearch/bin/plugin.new
  when: ansible_architecture == 'ppc64le'
  tags:
    - elasticsearch-patch-plugin
    - elesticsearch-install

- name: Overwrite plugin with patch
  command: mv plugin.new plugin
  args:
    chdir: /usr/share/elasticsearch/bin
    removes: /usr/share/elasticsearch/bin/plugin.new
  when: ansible_architecture == 'ppc64le'
  tags:
    - elasticsearch-patch-plugin
    - elesticsearch-install

- name: Make plugin executable again
  file:
    path: /usr/share/elasticsearch/bin/plugin
    mode: 0755
  when: ansible_architecture == 'ppc64le'
  tags:
    - elasticsearch-patch-plugin
    - elesticsearch-install

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: present
    extra_args: "{{ pip_install_options | default('') }}"
  register: install_pip_packages
  until: install_pip_packages|success
  retries: 5
  delay: 2
  with_items: "{{ elasticsearch_pip_packages }}"
  tags:
    - elasticsearch-pip-packages
    - elasticsearch-install

- name: Install ElasticHQ Plugin
  command: ./plugin install {{ item }}
  args:
    chdir: /usr/share/elasticsearch/bin
    creates: /usr/share/elasticsearch/plugins/hq
  retries: 5
  delay: 2
  with_items:
    - royrusso/elasticsearch-HQ/v2.0.3
  tags:
    - elasticsearch-plugins
    - elasticsearch-install

- name: Install Kopf Plugin
  command: ./plugin install {{ item }}
  args:
    chdir: /usr/share/elasticsearch/bin
    creates: /usr/share/elasticsearch/plugins/kopf
  retries: 5
  delay: 2
  with_items:
    - lmenezes/elasticsearch-kopf
  tags:
    - elasticsearch-plugins
    - elasticsearch-install

- name: Install Head Plugin
  command: ./plugin install {{ item }}
  args:
    chdir: /usr/share/elasticsearch/bin
    creates: /usr/share/elasticsearch/plugins/head
  retries: 5
  delay: 2
  with_items:
    - mobz/elasticsearch-head
  tags:
    - elasticsearch-plugins
    - elasticsearch-install

- name: Install ICU Analysis Plugin
  command: ./plugin install {{ item }}
  args:
    chdir: /usr/share/elasticsearch/bin
    creates: /usr/share/elasticsearch/plugins/analysis-icu
  retries: 5
  delay: 2
  with_items:
    - analysis-icu
  tags:
    - elasticsearch-plugins
    - elasticsearch-install

- name: Install Smart Chinese Analysis Plugin
  command: ./plugin install {{ item }}
  args:
    chdir: /usr/share/elasticsearch/bin
    creates: /usr/share/elasticsearch/plugins/analysis-smartcn
  retries: 5
  delay: 2
  with_items:
    - analysis-smartcn
  tags:
    - elasticsearch-plugins
    - elasticsearch-install

- name: Install lang-javascript Plugin
  command: ./plugin install {{ item }}
  args:
    chdir: /usr/share/elasticsearch/bin
    creates: /usr/share/elasticsearch/plugins/lang-javascript
  retries: 5
  delay: 2
  with_items:
    - lang-javascript
  tags:
    - elasticsearch-plugins
    - elasticsearch-install

- name: Install lang-python Plugin
  command: ./plugin install {{ item }}
  args: 
    chdir: /usr/share/elasticsearch/bin
    creates: /usr/share/elasticsearch/plugins/lang-python
  retries: 5
  delay: 2
  with_items:
    - lang-python
  tags:
    - elasticsearch-plugins
    - elasticsearch-install

- name: Install elasticsearch-paramedic Plugin
  command: ./plugin install {{ item }}
  args: 
    chdir: /usr/share/elasticsearch/bin
    creates: /usr/share/elasticsearch/plugins/paramedic
  retries: 5
  delay: 2
  with_items:
    - karmi/elasticsearch-paramedic
  tags:
    - elasticsearch-plugins
    - elasticsearch-install

- name: Enable ElasticSearch Service
  service:
    name: elasticsearch
    enabled: yes
