---
        - name: cleanup nagios core directory
          command: rm -rf {{ nagios_tmp_dir }}

        - name: cleanup nagios plugin directory
          command: rm -rf {{ plugin_tmp_dir }}

        - name: Installs all prereqs
          apt: name={{item}} state=present update_cache=true
          with_items: "{{nagios_packages_to_install}}"

        - name: Download Nagios Core
          get_url:
              url: "{{ nagios_download_site }}/{{ nagios_download_file }}"
              dest: "{{ download_dir }}"

        - name: Download Nagios Plugins
          get_url:
              url: "{{ plugin_download_site }}/{{ plugin_download_file }}" 
              dest: "{{ download_dir }}"

        - name: Create nagcmd group
          group: name=nagcmd state=present

        - name: Create nagios user and add him to the nagcmd group
          user: name=nagios groups=nagcmd

        - name: Extract nagios core
          unarchive: src=/tmp/{{ nagios_download_file }} dest={{ download_dir }}/ creates={{ nagios_tmp_dir }} copy=no

        - name: Extract nagios plugins
          unarchive: src=/tmp/{{ plugin_download_file }}  dest={{ download_dir }}/ creates={{ plugin_tmp_dir }} copy=no

        - name: Configure nagios core
          command: ./configure --with-nagios-group=nagios --with-command-group=nagcmd chdir={{ nagios_tmp_dir }}

        - name: make all
          command: make all chdir={{ nagios_tmp_dir }}

        - name: make install
          command: make install chdir={{ nagios_tmp_dir }}

        - name: make install-init
          command: make install-init chdir={{ nagios_tmp_dir }}

        - name: make install-config
          command: make install-config chdir={{ nagios_tmp_dir }}

        - name: make install-commandmode
          command: make install-commandmode chdir={{ nagios_tmp_dir }}

        - name: copy nagios conf to apache
          command: /usr/bin/install -c -m 644 sample-config/httpd.conf /etc/apache2/sites-enabled/nagios.conf chdir={{ nagios_tmp_dir }}

        - name: create nagiosadmin web user with password 
          command: htpasswd -c -b /usr/local/nagios/etc/htpasswd.users {{ nagiosadmin_user }} {{ nagiosadmin_password }}

        - name: configure nagios plugins
          command: ./configure --with-nagios-user=nagios --with-nagios-group=nagios chdir={{ plugin_tmp_dir }}
    
        - name: make plugins
          command: make chdir={{ plugin_tmp_dir }}

        - name: make install plugins
          command: make install chdir={{ plugin_tmp_dir }}

        - name: allow urls rewrites
          command: a2enmod rewrite

        - name: allow cgi-bins
          command: a2enmod cgi

#        - name: Make nagios start on boot
#          command: ln -sf /etc/init.d/nagios /etc/rcS.d/S99nagios

        - name: Add plugin check_mellanox_switch
          template:
              src: check_mellanox_switch
              dest: /usr/local/nagios/libexec
              mode: 0755

        - name: Add plugin check_rack_switch
          template:
              src: check_rack_switch
              dest: /usr/local/nagios/libexec
              mode: 0755
   
        - name: Validate Nagios Config
          command: /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg

        - name: Restart apache
          service: name=apache2 state=restarted enabled=yes

        - name: Restart nagios
          service: name=nagios state=restarted enabled=yes

        - name: cleanup nagios core directory
          command: rm -rf {{ nagios_tmp_dir }}

        - name: cleanup nagios plugin directory
          command: rm -rf {{ plugin_tmp_dir }}

