# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
temp_install_directory: /tmp/kibana_install

kibana_directory: kibana-5.3.0-linux-x86_64
nodejs_directory: node-v6.9.5-linux-ppc64le

kibana_packages:
  - { url: "https://artifacts.elastic.co/downloads/kibana",
      file: "kibana-5.3.0-linux-x86_64.tar.gz",
      directory: "{{ kibana_directory }}",
      checksum: "sha1:4e9daf275f8ef749fba931c1f5c35f85662efd53" }
  - { url: "http://nodejs.org/dist/v6.9.5",
      file: "node-v6.9.5-linux-ppc64le.tar.gz",
      directory: "{{ nodejs_directory }}",
      checksum: "sha1:f6beaac743e57df39eb022330dca4e331735ab61" }


