---
# Copyright 2017, IBM US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

elasticsearch_pre_packages:
  - apt-transport-https
  - wget
  - curl
  - rsync
  - python-pip

jre_repo_url: "http://ftp.us.debian.org/debian"

jre_repos:
  - { repo: "deb {{ jre_repo_url }} experimental main", state: "present" }
  - { repo: "deb {{ jre_repo_url }} sid main", state: "present" }

jre_package: openjdk-7-jre-headless

#preq for openjdk-7-jre-headless can't be found with apt-get
jre_preq_packages:
  - { url: "http://ftp.us.debian.org/debian/pool/main/libj/libjpeg-turbo", file: "libjpeg62-turbo_1.5.1-2_ppc64el.deb" }

#for ppc64le and x86 use the deb package to install
elasticsearch_packages:
  - { url: "https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.1", file: "elasticsearch-2.4.1.deb" }
