---
# Copyright 2017, IBM US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include: "{{ opsmgr_lib }}/util/osa.yml"

- hosts: localhost
  gather_facts: yes
  become: no

  vars:

    - recipe_name: "privatecloud-newton"
    - output_dir: "profile"
    - temp_dir: "/tmp/.opsmgr-{{ recipe_name }}"
    - genesis_dir: "/var/oprc"
    - osa_conf: "/etc/openstack_deploy"
    - osa_play: "/etc/ansible/roles"
    - osa_home: "/opt/openstack-ansible"
    - files_to_include:
        - "{{ osa_conf }}/user_secrets.yml"
        - "{{ osa_conf }}/openstack_user_config.yml"
        - "{{ osa_play }}/openstack_hosts/defaults/main.yml"
        - "{{ osa_play }}/os_horizon/defaults/main.yml"
        - "{{ osa_play }}/os_swift/defaults/main.yml"
        - "{{ osa_play }}/galera_client/defaults/main.yml"
        - "{{ osa_home }}/playbooks/inventory/group_vars/all.yml"
        - "{{ genesis_dir }}/inventory.yml" #Required for blacklist of ips

  tasks:

    - name: imports all necessary variables from OSA
      include_vars: "{{ item }}"
      with_items: "{{ files_to_include }}"

    - name: ensures output directory exists
      file: path={{ output_dir }} mode=0755 state=directory

    - name: Use OSA dynamic inventory to populate the variables
      template:
          src: "templates/vars.yml.j2"
          dest: "{{ output_dir }}/vars.yml"
