---
    - name: Installs prereqs from apt-get
      apt: name={{item}} state=present update_cache=true
      with_items: "{{container_packages_to_install}}"

    - name: Install lxc-python2 library for ansible
      pip: name=lxc-python2

    - name: Create nagios container
      lxc_container:
          name: "{{ container }}"
          template: ubuntu
          state: stopped
          template_options: --release trusty

    - name: Add static IP
      template:
          src: nagios_network_interface 
          dest: /var/lib/lxc/{{ container }}/rootfs/etc/network/interfaces
          mode: 0644
  
    - name: Create /root/.ssh directory
      file: 
          path: /var/lib/lxc/{{ container }}/rootfs/home/ubuntu/.ssh
          state: directory
          mode: 0700

    - name: Copy ssh key
      copy:
          src: ~/.ssh/id_rsa.pub
          dest: /var/lib/lxc/{{ container }}/rootfs/home/ubuntu/.ssh/authorized_keys
          mode: 0600

    - name: Start container, fix permissions, install python
      lxc_container:
        name: "{{ container }}"
        state: started
        container_command: |
            chown -R ubuntu:ubuntu /home/ubuntu
            apt-get install -y python

    - name: Create iptables rule to forward port 80
      command: iptables -t nat -A PREROUTING -p tcp -d {{ ansible_nodename }} --dport 80 -j DNAT --to {{ nagios_ip }}:80

# The follow is only valid with ansible 2.1
#
#  - name: Create iptables rule to forward port 80
#    iptables:
#        chain: PREROUTING
#        ctstate: DNAT
#        destination: "{{ ansible_nodename }}"
#        destination_port: 80
#        protocol: tcp
#        table: nat
#        to_destination: 10.0.3.10:80
