---
    - name: Installs prereqs from apt-get
      apt: name={{item}} state=present update_cache=true
      with_items: "{{container_packages_to_install}}"

    - name: Install lxc-python2 library for ansible
      pip: name=lxc-python2

    - name: Create nagios container
      lxc_container:
          name: "{{ container }}"
          template: ubuntu
          state: stopped
          template_options: --release trusty
          container_command: |
              mkdir -p /{{ container_directory_to_mount }}

    - name: Add static IP
      template:
          src: nagios_network_interface 
          dest: /var/lib/lxc/{{ container }}/rootfs/etc/network/interfaces
          mode: 0644
  
    - name: Create /root/.ssh directory
      file: 
          path: /var/lib/lxc/{{ container }}/rootfs/home/ubuntu/.ssh
          state: directory
          mode: 0700

    - name: Copy ssh key
      copy:
          src: ~/.ssh/id_rsa.pub
          dest: /var/lib/lxc/{{ container }}/rootfs/home/ubuntu/.ssh/authorized_keys
          mode: 0600

    - name: Validate the shared directory on the host is created
      file: path={{ host_directory_to_mount }} state=directory mode=0755

    - name: Edit the container config to mount the shared directory
      lineinfile:
          line: "lxc.mount.entry = {{ host_directory_to_mount }} {{ container_directory_to_mount }}  none rw,bind 0.0"
          dest: "/var/lib/lxc/{{ container }}/config"

    - name: Start container, fix permissions, install python
      lxc_container:
        name: "{{ container }}"
        state: started
        container_command: |
            chown -R ubuntu:ubuntu /home/ubuntu
            apt-get install -y python

    - name: Set container to autostart
      lineinfile:
          line: "lxc.start.auto = 1"
          dest: "/var/lib/lxc/{{ container }}/config"

    - name: nagios_http get iptables rules
      shell: iptables -t nat -L
      register: iptablesrules
      always_run: yes

    - name: Create iptables rule to forward port 80
      command: iptables -t nat -A PREROUTING -p tcp -d {{ ansible_nodename }} --dport 80 -j DNAT --to {{ nagios_ip }}:80 -m comment --comment "nagios_http"
      when: iptablesrules.stdout.find("nagios_http") == -1
 
    - name: Save the iptables change
      shell: iptables-save > /etc/iptables.rules
      
    - name: Load iptables on boot
      lineinfile:
          line: "pre-up iptables-restore < /etc/iptables.rules"
          dest: "/etc/network/interfaces"

# The follow is only valid with ansible 2.1
#
#  - name: Create iptables rule to forward port 80
#    iptables:
#        chain: PREROUTING
#        ctstate: DNAT
#        destination: "{{ ansible_nodename }}"
#        destination_port: 80
#        protocol: tcp
#        table: nat
#        to_destination: {{ nagios_ip }}:80
