---

# default vars

controller_ip: 127.0.0.1

install_mysql: True
db_login_user: "{{ ansible_ssh_user }}"
db_login_password: passw0rd
db_login_host: "{{ hostvars[inventory_hostname].hostaddr }}"
db_user: opsmgr
db_password: passw0rd
db_host: "{{ hostvars[inventory_hostname].hostaddr }}"

install_ui: False
ui_enabled: /etc/opsmgr/ui

import_containers: []

create_lxc_network: false
main_lxc_interface: eth0

lxc_container_default_mtu: 1500
address_pool: [ 172.29.236.41, 172.29.236.42, 172.29.236.43, 172.29.236.44, 172.29.236.45, 172.29.236.46, 172.29.236.47, 172.29.236.48, 172.29.236.49 ]

# lxc container networks
# defines additional networks to be created 
container_networks:
  - name: mgmt
    bridge: "br-mgmt"
    interface: "eth1"
    netmask: "255.255.252.0"
    type: "veth"




