---
# Copyright 2017, IBM US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Prepare folders
  file:
    path: /etc/httpd/sites-{{ item }}
    state: directory
  with_items:
    - available
    - enabled

- name: Link tls to ssl
  file:
    state: "link"
    src: "/etc/pki/tls/private"
    dest: "/etc/ssl/private"
    owner: "root"
    group: "root"

- name: Link /etc/apache2 to httpd
  file:
    state: "link"
    src: "/etc/httpd"
    dest: "/etc/apache2"
    owner: "root"
    group: "root"

- name: Enable configuration folder
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: IncludeOptional sites-enabled/*.conf

- name: Enable httpd Service
  service:
    name: httpd
    enabled: yes

- name: create self-signed SSL cert
  command: >
    openssl req -new -nodes -x509 -subj
    "/C=US/ST=Texas/L=San Antonio/O=IT/CN={{ kibana_server_name }}"
    -days 365
    -keyout /etc/ssl/private/apache.key
    -out /etc/ssl/certs/apache.cert
    -extensions v3_ca
    creates=/etc/ssl/certs/apache.cert
  when: kibana_self_signed is defined and kibana_self_signed == true
  tags:
    - kibana-self-signed-cert
    - kibana-post-install

- name: Comment Listen 80 in httpd.conf
  replace:
    dest: /etc/httpd/conf/httpd.conf
    regexp: "Listen 80"
    replace: "#Listen 80"

- name: Template Kibana Apache Config
  template:
    src: "{{ item }}"
    dest: "/etc/httpd/sites-available/{{ item }}"
    owner: "root"
    group: "root"
  with_items:
    - 000-kibana.conf
  notify: Restart Apache
  tags:
    - kibana-apache
    - kibana-post-install

- name: Drop Apache2 Ports File
  template:
    src: "{{ item }}"
    dest: "/etc/apache2/conf.d/{{ item }}"
    owner: "root"
    group: "root"
  with_items:
    - ports.conf
  notify: Restart Apache
  tags:
    - kibana-apache
    - kibana-post-install

- name: Link Kibana Site
  file:
    state: "link"
    src: "/etc/httpd/sites-available/000-kibana.conf"
    dest: "/etc/httpd/sites-enabled/000-kibana.conf"
    owner: "root"
    group: "root"
  notify: Restart Apache
  tags:
    - kibana-apache
    - kibana-post-install

- name: Remove Apache Default Site
  file:
    state: "absent"
    path: "/etc/httpd/sites-enabled/000-default.conf"
  notify: Restart Httpd
  tags:
    - kibana-apache
    - kibana-config

- name: Create kibana http_auth user
  htpasswd:
    path: "/etc/apache2/users"
    name: "kibana"
    password: "{{ opsmgr_kibana_password | default(kibana_password) }}"
    owner: "root"
    group: "apache"
    mode: "0640"
    create: "yes"
    state: "present"
  notify: Restart Apache
  tags:
    - kibana-apache
    - kibana-post-install

# open firewall port 8443 for access to kibana https
- name: open firewall rules
  firewalld:
    port: "{{ kibana_ssl_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  tags:
    - kibana-apache
    - kibana-post-install
