---

- hosts: opsmgr_hosts
  become: true
  vars_files:
    - [ ../ext/overrides.yml, defaults/main.yml ]
    - [ ../ext/shared.yml, defaults/shared.yml ]
    - vars/main.yml
  roles:
    - host

- hosts: localhost
  gather_facts: no
  connection: local
  become: false
  vars_files:
    - vars/main.yml
  tasks:
    - name: ensure etc directory exists
      command: mkdir -p {{ playbook_dir }}/ext
    - name: clean shared file
      file:
          path: "{{ playbook_dir }}/ext/vars.yml"
          state: absent
    - name: insert list of containers to shared file
      assemble:
          src: "{{ playbook_dir }}/ext/lxcs/"
          dest: "{{ playbook_dir }}/ext/shared.yml"
    - name: update shared file with a header
      lineinfile:
          dest: "{{ playbook_dir }}/ext/shared.yml"
          line: "opsmgr_containers:"
          insertbefore: BOF
    - name: remove temporary directory
      file: path={{ playbook_dir }}/ext/lxcs state=absent
    - name: copy shared file to ext directory
      copy:
          src: "{{ playbook_dir }}/ext/shared.yml"
          dest: "{{ opsmgr_dir }}/ext/shared.yml"

