---

- hosts: opsmgr_hosts
  become: true
  vars_files:
    - [ ../ext/overrides.yml, defaults/main.yml ]
    - [ ../ext/shared.yml, defaults/shared.yml ]
    - vars/main.yml
  roles:
    - host

- hosts: localhost
  gather_facts: no
  connection: local
  become: false
  tasks:
    - name: ensure etc directory exists
      become: false
      file:
          path: "{{ playbook_dir }}/etc"
          state: directory
    - name: clean extra-vars file
      become: false
      file:
          path: "{{ playbook_dir }}/../ext/shared.yml"
          state: absent
    - name: create extra-vars file
      become: false
      template:
          src: "{{ playbook_dir }}/roles/host/templates/shared.yml.j2"
          dest: "{{ playbook_dir }}/../ext/shared.yml"


