---
- hosts: opsmgr_hosts
  become: true
  vars_files:
    - vars/containers.yml
    - roles/host/vars/main.yml
  roles:
    - host

- hosts: localhost
  become: false
  tasks:
    - name: clean extra-vars file
      become: false
      file:
          path: "{{ playbook_dir }}/etc/vars.yml"
          state: absent
    - name: create extra-vars file
      become: false
      template:
          src: "{{ playbook_dir }}/roles/host/templates/spec.vars.j2"
          dest: "{{ playbook_dir }}/etc/vars.yml"


