---

- hosts: all
  gather_facts: yes
  become: true
  vars_files:
    - [ ../ext/overrides.yml, defaults/main.yml ]
    - [ ../ext/shared.yml, defaults/shared.yml ]
    - vars/main.yml
  roles:
    - provisioned

- hosts: localhost
  gather_facts: no
  connection: local
  become: false
  vars_files:
    - [ ../ext/overrides.yml, defaults/main.yml ]
    - [ ../ext/shared.yml, defaults/shared.yml ]
    - vars/main.yml
  pre_tasks:
    - include: tasks/import.yml
  roles:
    - provisioner


