---
- hosts: opsmgr_hosts
  become: true
  vars_files:
    - [ ../ext/overrides.yml, defaults/main.yml ]
    - [ ../ext/shared.yml, defaults/shared.yml ]
    - vars/main.yml

  tasks:

    #- name: start containers if stopped
    #  lxc_container:
    #      name: "{{ ansible_hostname }}-{{ item.name }}"
    #      state: started
    #  with_items: "{{ containers }}"
    #  register: lxc_info

    - name: destroy containers
      lxc_container:
          name: "{{ ansible_hostname }}-{{ item.name }}"
          state: absent
      with_items: "{{ containers }}"

    - name: shows container information on the screen
      debug: msg="removed lxc container {{ ansible_hostname }}-{{ item.name }}"
      with_items: "{{ containers }}"

- hosts: localhost
  become: false
  gather_facts: no
  vars_files:
    - vars/main.yml
  tasks:
    - name: clean shared file
      file:
          path: "{{ opsmgr_dir }}/ext/shared.yml"
          state: absent

