---
- hosts: opsmgr_hosts
  become: true
  vars_files:
    - [ ../ext/overrides.yml, defaults/main.yml ]
    - [ ../ext/shared.yml, defaults/shared.yml ]
    - vars/main.yml

  tasks:

    - name: get iptables rules
      shell: iptables -t nat -L
      register: iptablesrules
      always_run: yes

    - name: create iptables prerouting rule to forward port to container
      command: |
          iptables -t nat -D PREROUTING -p tcp
          -d {{ item.0.hostaddr }} --dport {{ item.1.host }} -j DNAT
          --to {{ item.0.address }}:{{ item.1.container }} -m comment
          --comment "opsmgr-{{ item.0.hostname }}-{{ item.1.name }}"
      when: |
          iptablesrules.stdout.find("opsmgr-{{ item.0.hostname }}-{{ item.1.name }}") != -1
      with_subelements:
        - "{{ opsmgr_containers }}"
        - ports

    - name: create iptables masquerade rule to allow mysql connection
      command: |
          iptables -t nat -D POSTROUTING -p tcp
          -d "{{ item.0.address }}/32" --dport {{ item.1.host }} -j MASQUERADE
          -m comment --comment "opsmgr-{{ item.0.hostname }}-masq"
      when: |
          item.1.name == 'mysql' and
          iptablesrules.stdout.find("opsmgr-{{ item.0.hostname }}-masq") != -1
      with_subelements:
        - "{{ opsmgr_containers }}"
        - ports

    - name: save the iptables change
      shell: iptables-save > /etc/iptables.rules


